export interface Voter {
    boothCode: string,
    serialNo: number,
    voterName: string,
    guardianName: string,
    houseNo: string,
    address: string,
    gender: string,
    age: number,
    idCardNo: string,
    phoneNo: string,
    religion: string,
    caste: string,
    outOfStation: boolean,
    outOfWard: boolean,
    dead: boolean,
    voted: boolean,
    panchayatVote: string,
    blockVote: string,
    districtVote: string
}